### ISSUE TITLE
Wrong removal of some references

### ISSUE THREAD

**Issue by claudiuconstantin** [subatta/ResolveUR#1]
I encountered a use case where the extension removes a reference, but it shouldn't. It's Apache.NMS.ActiveMQ dll (version 1.7.1.3924) referenced via the [nuget package](https://www.nuget.org/packages/Apache.NMS.ActiveMQ/). The problem is that even the project compiles after it's removal, you'll receive an exception in the project when you try something like:

`IConnectionFactory factory = new NMSConnectionFactory(connecturi);`

A potential solution would be a mapping-list of exceptions like this one?

**Comment by claudiuconstantin** [comment]
The same exact thing for System.Configuration.Abstractions.dll.

**Comment by claudiuconstantin** [comment]
A potential solution would be a list of exceptions: one should be able to right-click a reference, then click "Add to removal exceptions" or something like that.

**Comment by pratyak1** [comment]
@Sure, I'll add this to the list of things to be exempted. Nuget packages are on there.

**Comment by SteveK-GS** [comment]
Additionally, the tool seems to be removing Nuget packages which have developmentDependency="true" in Nuget.config. A good example would be Fody, which is not _referenced_ but is _used_ at compile time. The simple fix would be never to remove packages labelled as development dependencies.

Other than that, what a great tool! Thank you for providing it.

**Comment by pratyak1** [comment]
Hate that I didn't see your comment @SteveK-GS.

The update has been done to accommodate preview, exclusion of references and final confirmation. I'll take care of the developmentDependency in an update shortly.

**Comment by pratyak1** [comment]
Done. @claudiuconstantin: I took the idea of Git's interactive rebase and made the exclusion list easy to specify.
