### ISSUE TITLE
Visual Studio 2017 support

### ISSUE THREAD

**Issue by SangAdv** [subatta/ResolveUR#3]
Do you have plans to support VS 2017 in the future?

Thank you for a great tool. It worked really well under VS 2015.

**Comment by pratyak1** [comment]
It's ready but the Edit Extension link is broken on the MarketPlace portal. It redirects back to the page instead of the upload form.

**Comment by pratyak1** [comment]
published 3.2

**Comment by SangAdv** [comment]
Thanks Suresh. Really appreciate your efforts.
