### ISSUE TITLE
Project references not being removed

### ISSUE THREAD

**Issue by SteveK-GS** [subatta/ResolveUR#4]
- Run ResolveUR on a project with an unused reference to a .csproj with a relative path
- refs.txt opens in Notepad; the unused project reference is listed along with any unused binary references
- Close Notepad without making any change to the file
- Answer yes to the dialog "Continue with removal of unused references?"
- The csproj reference is not removed

Visual Studio 2015 Update 3; ResolveUR v3.1

**Comment by pratyak1** [comment]
Thanks for reporting.

**Comment by pratyak1** [comment]
Fixed.
